name: Steam Profile Lookup

on:
  repository_dispatch:
    types: [lookup]

jobs:
  lookup_profile:
    runs-on: ubuntu-latest
    steps:
      - name: Lookup Steam Profile
        id: lookup
        run: |
          STEAM_API_KEY=${{ secrets.STEAM_WEB_API_KEY }}
          STEAM_ID=${{ github.event.client_payload.steamId }}

          echo "Looking up SteamID: $STEAM_ID"
          RESPONSE=$(curl -s "https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=$STEAM_API_KEY&steamids=$STEAM_ID")
          PROFILEURL=$(echo "$RESPONSE" | jq -r '.response.players[0].profileurl')

          echo "profileUrl=$PROFILEURL" >> $GITHUB_OUTPUT
        env:
          STEAM_WEB_API_KEY: ${{ secrets.STEAM_WEB_API_KEY }}

      - name: Output Profile URL
        run: echo "Profile URL: ${{ steps.lookup.outputs.profileUrl }}"
